language: rust
env:
  - RUST_LOG=warn
script:
  - cargo build --verbose --all
  - cargo test --verbose --all


rust:
  - stable
  - beta
  - nightly

notifications:
  slack:
    rooms:
      - pauni:dbpXKu6ldWOjEWqKyL4IbDxK#general
      - pauni:dbpXKu6ldWOjEWqKyL4IbDxK#ci
