language: rust
#env:
#  - RUST_LOG=warn
#  - RUST_BACKTRACE=1

#script:
#  - cargo build --all
#  - cargo test --all

before_install:
  - sudo apt-get -y update
  - sudo apt-get -y install libdbus-1-dev libgtk-3-dev

rust:
  - stable
  - beta
  - nightly
